package hibernate;
// Generated Apr 1, 2020 9:05:24 PM by Hibernate Tools 4.3.1



/**
 * Biodata generated by hbm2java
 */
public class Biodata  implements java.io.Serializable {


     private int idbiodata;
     private String nama;
     private String jeniskelamin;

    public Biodata() {
    }

	
    public Biodata(int idbiodata) {
        this.idbiodata = idbiodata;
    }
    public Biodata(int idbiodata, String nama, String jeniskelamin) {
       this.idbiodata = idbiodata;
       this.nama = nama;
       this.jeniskelamin = jeniskelamin;
    }
   
    public int getIdbiodata() {
        return this.idbiodata;
    }
    
    public void setIdbiodata(int idbiodata) {
        this.idbiodata = idbiodata;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getJeniskelamin() {
        return this.jeniskelamin;
    }
    
    public void setJeniskelamin(String jeniskelamin) {
        this.jeniskelamin = jeniskelamin;
    }




}


