package hibernate;
// Generated Apr 1, 2020 9:05:24 PM by Hibernate Tools 4.3.1



/**
 * Cek generated by hbm2java
 */
public class Cek  implements java.io.Serializable {


     private int idcek;
     private String hasil;

    public Cek() {
    }

	
    public Cek(int idcek) {
        this.idcek = idcek;
    }
    public Cek(int idcek, String hasil) {
       this.idcek = idcek;
       this.hasil = hasil;
    }
   
    public int getIdcek() {
        return this.idcek;
    }
    
    public void setIdcek(int idcek) {
        this.idcek = idcek;
    }
    public String getHasil() {
        return this.hasil;
    }
    
    public void setHasil(String hasil) {
        this.hasil = hasil;
    }




}


